-- Run this in Supabase SQL Editor.
-- Creates auth/purchase activity tables and policies for browser-side inserts.

create table if not exists public.auth_activity_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  visitor_id text not null,
  user_id uuid null references auth.users(id) on delete set null,
  email text null,
  action text not null,
  outcome text not null,
  provider text null,
  source_page text null,
  detail text null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists auth_activity_log_occurred_at_idx on public.auth_activity_log (occurred_at desc);
create index if not exists auth_activity_log_email_idx on public.auth_activity_log (email);
create index if not exists auth_activity_log_action_idx on public.auth_activity_log (action);

alter table public.auth_activity_log enable row level security;

drop policy if exists "auth activity insert public" on public.auth_activity_log;
create policy "auth activity insert public"
on public.auth_activity_log
for insert
to anon, authenticated
with check (true);

create table if not exists public.purchase_activity_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  visitor_id text not null,
  user_id uuid null references auth.users(id) on delete set null,
  email text null,
  invoice_no text null,
  order_ref text null,
  stage text not null,
  outcome text not null,
  payment_provider text null,
  payment_status text null,
  amount_total numeric(12,2) null,
  currency text null default 'ZAR',
  product text null,
  quantity integer null,
  source_page text null,
  detail text null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists purchase_activity_log_occurred_at_idx on public.purchase_activity_log (occurred_at desc);
create index if not exists purchase_activity_log_invoice_idx on public.purchase_activity_log (invoice_no);
create index if not exists purchase_activity_log_stage_idx on public.purchase_activity_log (stage);

alter table public.purchase_activity_log enable row level security;

drop policy if exists "purchase activity insert public" on public.purchase_activity_log;
create policy "purchase activity insert public"
on public.purchase_activity_log
for insert
to anon, authenticated
with check (true);

-- Orders table is already used in js/private-payment.js.
-- Keep/adjust your existing orders table schema to include invoice_no and payment fields.
