-- Run this in Supabase SQL Editor after link-card-schema.sql.
-- Service-side helper used by sync-cardholder-profiles Edge Function.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.cardholder_profile_urls (
  id bigint generated by default as identity primary key,
  card_email text not null,
  profile_slug text not null,
  display_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cardholder_profile_urls_email_key unique (card_email),
  constraint cardholder_profile_urls_slug_key unique (profile_slug),
  constraint cardholder_profile_urls_email_format check (card_email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  constraint cardholder_profile_urls_slug_format check (profile_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

alter table public.cardholder_profile_urls
  add column if not exists display_name text not null default '';
alter table public.cardholder_profile_urls
  add column if not exists created_at timestamptz not null default now();
alter table public.cardholder_profile_urls
  add column if not exists updated_at timestamptz not null default now();

create index if not exists cardholder_profile_urls_email_idx on public.cardholder_profile_urls (card_email);
create index if not exists cardholder_profile_urls_slug_idx on public.cardholder_profile_urls (profile_slug);

drop trigger if exists cardholder_profile_urls_set_updated_at on public.cardholder_profile_urls;
create trigger cardholder_profile_urls_set_updated_at
before update on public.cardholder_profile_urls
for each row
execute function public.set_updated_at();

alter table public.cardholder_profile_urls enable row level security;

drop policy if exists "cardholder profile urls manager read" on public.cardholder_profile_urls;
create policy "cardholder profile urls manager read"
on public.cardholder_profile_urls
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'check.email@residue.com');

create or replace function public.ensure_profile_for_auth_email(
  p_email text,
  p_display_name text default null,
  p_preferred_slug text default null
)
returns table (
  profile_id uuid,
  auth_email text,
  name text,
  slug text
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_email text;
  v_user_id uuid;
  v_display_name text;
  v_reserved_slug text;
  v_base_slug text;
  v_current_slug text;
  v_has_links boolean;
  v_slug text;
  v_suffix integer := 2;
begin
  v_email := lower(trim(coalesce(p_email, '')));
  if v_email = '' or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Invalid email';
  end if;

  select u.id
  into v_user_id
  from auth.users u
  where lower(u.email) = v_email
  order by u.created_at asc
  limit 1;

  if v_user_id is null then
    raise exception 'No auth user exists for %', v_email;
  end if;

  v_display_name := nullif(trim(coalesce(p_display_name, '')), '');

  select cpu.profile_slug
  into v_reserved_slug
  from public.cardholder_profile_urls cpu
  where cpu.card_email = v_email
  limit 1;

  v_base_slug := regexp_replace(
    lower(coalesce(v_reserved_slug, nullif(trim(p_preferred_slug), ''), split_part(v_email, '@', 1))),
    '[^a-z0-9]+',
    '-',
    'g'
  );
  v_base_slug := regexp_replace(v_base_slug, '(^-+|-+$)', '', 'g');

  if v_base_slug = '' then
    v_base_slug := 'user-' || left(replace(v_user_id::text, '-', ''), 8);
  end if;

  if exists (select 1 from public.profiles p where p.id = v_user_id) then
    select
      p.slug,
      exists(select 1 from public.links l where l.profile_id = v_user_id)
    into v_current_slug, v_has_links
    from public.profiles p
    where p.id = v_user_id;

    v_slug := v_current_slug;
    if nullif(trim(coalesce(p_preferred_slug, '')), '') is not null and not coalesce(v_has_links, false) then
      v_slug := v_base_slug;
      v_suffix := 2;
      while exists (select 1 from public.profiles p where p.slug = v_slug and p.id <> v_user_id)
        or exists (
          select 1
          from public.cardholder_profile_urls cpu
          where cpu.profile_slug = v_slug
            and cpu.card_email <> v_email
        )
      loop
        v_slug := v_base_slug || '-' || v_suffix::text;
        v_suffix := v_suffix + 1;
      end loop;
    end if;

    update public.profiles p
    set
      auth_email = v_email,
      name = case
        when v_display_name is null then p.name
        when p.name is null or p.name = '' or p.name = 'Your name' or p.name = p.auth_email then v_display_name
        else p.name
      end,
      slug = coalesce(v_slug, p.slug)
    where p.id = v_user_id;

    return query
    select p.id, p.auth_email, p.name, p.slug
    from public.profiles p
    where p.id = v_user_id;
    return;
  end if;

  v_slug := v_base_slug;
  while exists (select 1 from public.profiles p where p.slug = v_slug)
    or exists (
      select 1
      from public.cardholder_profile_urls cpu
      where cpu.profile_slug = v_slug
        and cpu.card_email <> v_email
    )
  loop
    v_slug := v_base_slug || '-' || v_suffix::text;
    v_suffix := v_suffix + 1;
  end loop;

  insert into public.profiles (id, auth_email, name, slug, theme)
  values (
    v_user_id,
    v_email,
    coalesce(v_display_name, v_email, 'Residue User'),
    v_slug,
    'light'
  );

  return query
  select p.id, p.auth_email, p.name, p.slug
  from public.profiles p
  where p.id = v_user_id;
end;
$$;

revoke all on function public.ensure_profile_for_auth_email(text, text, text) from public;
revoke all on function public.ensure_profile_for_auth_email(text, text, text) from anon;
revoke all on function public.ensure_profile_for_auth_email(text, text, text) from authenticated;
grant execute on function public.ensure_profile_for_auth_email(text, text, text) to service_role;

-- profiles.id historically referenced auth.users(id). Secondary cardholders
-- need a durable profile and URL before they choose to create a login, so allow
-- service-created profile UUIDs that are not Auth identities.
do $$
declare
  v_constraint record;
begin
  for v_constraint in
    select c.conname
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'profiles'
      and c.contype = 'f'
      and pg_get_constraintdef(c.oid) ilike '%references auth.users%'
  loop
    execute format('alter table public.profiles drop constraint %I', v_constraint.conname);
  end loop;
end $$;

create or replace function public.ensure_secondary_cardholder_profile(
  p_email text,
  p_display_name text default null,
  p_preferred_slug text default null
)
returns table (
  profile_id uuid,
  auth_email text,
  name text,
  slug text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text;
  v_name text;
  v_reserved_slug text;
  v_base_slug text;
  v_slug text;
  v_suffix integer := 2;
  v_id uuid;
begin
  v_email := lower(trim(coalesce(p_email, '')));
  if v_email = '' or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Invalid email';
  end if;

  select p.id into v_id
  from public.profiles p
  where lower(p.auth_email) = v_email
  order by p.created_at asc
  limit 1;

  if v_id is not null then
    return query
    select p.id, p.auth_email, p.name, p.slug
    from public.profiles p
    where p.id = v_id;
    return;
  end if;

  v_name := coalesce(nullif(trim(p_display_name), ''), split_part(v_email, '@', 1), 'Residue User');
  select cpu.profile_slug into v_reserved_slug
  from public.cardholder_profile_urls cpu
  where cpu.card_email = v_email
  limit 1;

  v_base_slug := regexp_replace(
    lower(coalesce(v_reserved_slug, nullif(trim(p_preferred_slug), ''), split_part(v_email, '@', 1))),
    '[^a-z0-9]+',
    '-',
    'g'
  );
  v_base_slug := regexp_replace(v_base_slug, '(^-+|-+$)', '', 'g');
  if v_base_slug = '' then
    v_base_slug := 'cardholder';
  end if;

  v_slug := v_base_slug;
  while exists (select 1 from public.profiles p where p.slug = v_slug) loop
    v_slug := v_base_slug || '-' || v_suffix::text;
    v_suffix := v_suffix + 1;
  end loop;

  insert into public.profiles (id, auth_email, name, slug, theme)
  values (gen_random_uuid(), v_email, v_name, v_slug, 'light')
  returning id into v_id;

  return query
  select p.id, p.auth_email, p.name, p.slug
  from public.profiles p
  where p.id = v_id;
end;
$$;

revoke all on function public.ensure_secondary_cardholder_profile(text, text, text) from public;
revoke all on function public.ensure_secondary_cardholder_profile(text, text, text) from anon;
revoke all on function public.ensure_secondary_cardholder_profile(text, text, text) from authenticated;
grant execute on function public.ensure_secondary_cardholder_profile(text, text, text) to service_role;

create or replace function public.ensure_profile_from_auth(
  p_user_id uuid,
  p_email text,
  p_display_name text default null
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_email text;
  v_display_name text;
  v_reserved_slug text;
  v_base_slug text;
  v_slug text;
  v_suffix integer := 2;
begin
  if p_user_id is null then
    return;
  end if;

  v_email := lower(trim(coalesce(p_email, '')));
  v_display_name := nullif(trim(coalesce(p_display_name, '')), '');

  if exists (select 1 from public.profiles where id = p_user_id) then
    update public.profiles
    set auth_email = case when v_email <> '' then v_email else auth_email end
    where id = p_user_id;
    return;
  end if;

  select cpu.profile_slug
  into v_reserved_slug
  from public.cardholder_profile_urls cpu
  where cpu.card_email = v_email
  limit 1;

  v_base_slug := regexp_replace(
    lower(coalesce(v_reserved_slug, split_part(v_email, '@', 1))),
    '[^a-z0-9]+',
    '-',
    'g'
  );
  v_base_slug := regexp_replace(v_base_slug, '(^-+|-+$)', '', 'g');
  if v_base_slug = '' then
    v_base_slug := 'user-' || left(replace(p_user_id::text, '-', ''), 8);
  end if;

  v_slug := v_base_slug;
  while exists (select 1 from public.profiles p where p.slug = v_slug)
    or exists (
      select 1
      from public.cardholder_profile_urls cpu
      where cpu.profile_slug = v_slug
        and cpu.card_email <> v_email
    )
  loop
    v_slug := v_base_slug || '-' || v_suffix::text;
    v_suffix := v_suffix + 1;
  end loop;

  insert into public.profiles (id, auth_email, name, slug, theme)
  values (
    p_user_id,
    case when v_email <> '' then v_email else null end,
    coalesce(v_display_name, nullif(v_email, ''), 'Residue User'),
    v_slug,
    'light'
  );
end;
$$;

-- Secondary cardholders are created by the sync Edge Function and are followed
-- immediately by ensure_profile_for_auth_email(). Skip the general signup
-- bootstrap for those service-created users so a trigger-side profile error
-- cannot roll back the Auth identity before the dedicated RPC runs.
create or replace function public.on_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if coalesce(new.raw_user_meta_data ->> 'residue_cardholder', 'false') = 'true' then
    return new;
  end if;

  perform public.ensure_profile_from_auth(
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', null)
  );
  return new;
end;
$$;

drop trigger if exists auth_users_profile_bootstrap on auth.users;
create trigger auth_users_profile_bootstrap
after insert on auth.users
for each row
execute function public.on_auth_user_created();
