-- Run this in Supabase SQL Editor.
-- Creates Residue link-card tables and policies.
-- Card/profile data is tied to the signed-in auth user and email.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  auth_email text,
  name text not null default '',
  slug text not null unique,
  title text,
  bio text,
  avatar_url text,
  theme text not null default 'dark',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint profiles_theme_check check (theme in ('dark', 'light'))
);

alter table public.profiles
  add column if not exists auth_email text;
alter table public.profiles
  add column if not exists name text not null default '';
alter table public.profiles
  add column if not exists slug text;
alter table public.profiles
  add column if not exists title text;
alter table public.profiles
  add column if not exists bio text;
alter table public.profiles
  add column if not exists avatar_url text;
alter table public.profiles
  add column if not exists theme text not null default 'dark';
alter table public.profiles
  add column if not exists created_at timestamptz not null default now();
alter table public.profiles
  add column if not exists updated_at timestamptz not null default now();

update public.profiles
set slug = coalesce(nullif(slug, ''), split_part(coalesce(auth_email, ''), '@', 1))
where slug is null or slug = '';

update public.profiles p
set auth_email = lower(u.email)
from auth.users u
where p.id = u.id
  and (p.auth_email is null or p.auth_email = '');

with normalized as (
  select
    id,
    coalesce(
      nullif(
        regexp_replace(
          regexp_replace(
            lower(coalesce(slug, split_part(coalesce(auth_email, ''), '@', 1), '')),
            '[^a-z0-9]+',
            '-',
            'g'
          ),
          '(^-+|-+$)',
          '',
          'g'
        ),
        ''
      ),
      'user-' || left(replace(id::text, '-', ''), 8)
    ) as base_slug
  from public.profiles
),
deduped as (
  select
    id,
    case
      when row_number() over (partition by base_slug order by id) = 1 then base_slug
      else base_slug || '-' || row_number() over (partition by base_slug order by id)
    end as final_slug
  from normalized
)
update public.profiles p
set slug = d.final_slug
from deduped d
where p.id = d.id
  and p.slug is distinct from d.final_slug;

alter table public.profiles
  alter column auth_email type text using lower(auth_email);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_auth_email_key'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_auth_email_key unique (auth_email);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_slug_key'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_slug_key unique (slug);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_slug_format'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_theme_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_theme_check check (theme in ('dark', 'light'));
  end if;
end $$;

create index if not exists profiles_auth_email_idx on public.profiles (auth_email);
create index if not exists profiles_slug_idx on public.profiles (slug);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  label text not null default 'Link',
  url text not null,
  sort integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists links_profile_id_sort_idx on public.links (profile_id, sort);

create table if not exists public.codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  owner_profile uuid not null references public.profiles(id) on delete cascade,
  max_uses integer not null default 5 check (max_uses > 0),
  used_count integer not null default 0 check (used_count >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists codes_owner_profile_idx on public.codes (owner_profile);
create index if not exists codes_code_idx on public.codes (code);

create table if not exists public.card_configs (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  auth_email text,
  config_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists card_configs_auth_email_idx on public.card_configs (auth_email);

alter table public.card_configs
  add column if not exists auth_email text;
alter table public.card_configs
  add column if not exists config_data jsonb not null default '{}'::jsonb;
alter table public.card_configs
  add column if not exists created_at timestamptz not null default now();
alter table public.card_configs
  add column if not exists updated_at timestamptz not null default now();

update public.card_configs c
set auth_email = lower(u.email)
from auth.users u
where c.profile_id = u.id
  and (c.auth_email is null or c.auth_email = '');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create or replace function public.sync_profile_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.auth_email := lower(coalesce(new.auth_email, (select email from auth.users where id = new.id)));
  return new;
end;
$$;

drop trigger if exists profiles_sync_auth_email on public.profiles;
create trigger profiles_sync_auth_email
before insert or update on public.profiles
for each row
execute function public.sync_profile_email();

alter table public.profiles enable row level security;
alter table public.links enable row level security;
alter table public.codes enable row level security;
alter table public.card_configs enable row level security;

drop policy if exists "profiles public read by slug" on public.profiles;
create policy "profiles public read by slug"
on public.profiles
for select
to anon, authenticated
using (true);

drop policy if exists "profiles owner write" on public.profiles;
create policy "profiles owner write"
on public.profiles
for all
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "links public read" on public.links;
create policy "links public read"
on public.links
for select
to anon, authenticated
using (true);

drop policy if exists "links owner write" on public.links;
create policy "links owner write"
on public.links
for all
to authenticated
using (auth.uid() = profile_id)
with check (auth.uid() = profile_id);

drop policy if exists "codes owner read write" on public.codes;
create policy "codes owner read write"
on public.codes
for all
to authenticated
using (auth.uid() = owner_profile)
with check (auth.uid() = owner_profile);

drop policy if exists "card configs owner read write" on public.card_configs;
create policy "card configs owner read write"
on public.card_configs
for all
to authenticated
using (auth.uid() = profile_id)
with check (auth.uid() = profile_id);

create or replace function public.create_code_for_user(p_owner uuid)
returns public.codes
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_row public.codes;
begin
  if auth.uid() is distinct from p_owner then
    raise exception 'Not allowed to create code for this user';
  end if;

  loop
    v_code := 'R-' || lpad((floor(random() * 10000))::int::text, 4, '0');
    begin
      insert into public.codes (code, owner_profile, max_uses, used_count, active)
      values (v_code, p_owner, 5, 0, true)
      returning * into v_row;
      return v_row;
    exception
      when unique_violation then
        -- retry on collision
    end;
  end loop;
end;
$$;

grant execute on function public.create_code_for_user(uuid) to authenticated;

create or replace function public.ensure_profile_from_auth(
  p_user_id uuid,
  p_email text,
  p_display_name text default null
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_email text;
  v_base_slug text;
  v_slug text;
  v_suffix integer := 0;
begin
  if p_user_id is null then
    return;
  end if;

  v_email := lower(coalesce(p_email, ''));

  if exists (select 1 from public.profiles where id = p_user_id) then
    update public.profiles
    set auth_email = case when v_email <> '' then v_email else auth_email end
    where id = p_user_id;
    return;
  end if;

  v_base_slug := regexp_replace(split_part(v_email, '@', 1), '[^a-z0-9]+', '-', 'g');
  v_base_slug := regexp_replace(v_base_slug, '(^-+|-+$)', '', 'g');
  if v_base_slug = '' then
    v_base_slug := 'user-' || left(replace(p_user_id::text, '-', ''), 8);
  end if;

  v_slug := v_base_slug;
  while exists (select 1 from public.profiles where slug = v_slug) loop
    v_suffix := v_suffix + 1;
    v_slug := v_base_slug || '-' || v_suffix::text;
  end loop;

  insert into public.profiles (id, auth_email, name, slug, theme)
  values (
    p_user_id,
    case when v_email <> '' then v_email else null end,
    coalesce(nullif(p_display_name, ''), nullif(v_email, ''), 'Residue User'),
    v_slug,
    'dark'
  );
end;
$$;

create or replace function public.on_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  perform public.ensure_profile_from_auth(
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', null)
  );
  return new;
end;
$$;

drop trigger if exists auth_users_profile_bootstrap on auth.users;
create trigger auth_users_profile_bootstrap
after insert on auth.users
for each row
execute function public.on_auth_user_created();

do $$
declare
  u record;
begin
  for u in
    select
      au.id,
      au.email,
      coalesce(au.raw_user_meta_data ->> 'full_name', au.raw_user_meta_data ->> 'name', null) as display_name
    from auth.users au
    left join public.profiles p on p.id = au.id
    where p.id is null
  loop
    perform public.ensure_profile_from_auth(u.id, u.email, u.display_name);
  end loop;
end $$;
