-- Run this in Supabase SQL Editor after link-card-schema.sql.
-- Stores admin-created card/account allocations separately from paid invoices.

create extension if not exists pgcrypto;

create table if not exists public.manual_card_allocations (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  quote_reference text not null default '',
  admin_note text not null default '',
  account_email text not null default '',
  account_name text not null default '',
  created_by_email text not null default '',
  updated_by_email text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint manual_card_allocations_profile_key unique (profile_id)
);

alter table public.manual_card_allocations
  add column if not exists quantity integer not null default 0;
alter table public.manual_card_allocations
  add column if not exists quote_reference text not null default '';
alter table public.manual_card_allocations
  add column if not exists admin_note text not null default '';
alter table public.manual_card_allocations
  add column if not exists account_email text not null default '';
alter table public.manual_card_allocations
  add column if not exists account_name text not null default '';
alter table public.manual_card_allocations
  add column if not exists created_by_email text not null default '';
alter table public.manual_card_allocations
  add column if not exists updated_by_email text not null default '';
alter table public.manual_card_allocations
  add column if not exists created_at timestamptz not null default now();
alter table public.manual_card_allocations
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'manual_card_allocations_quantity_check'
      and conrelid = 'public.manual_card_allocations'::regclass
  ) then
    alter table public.manual_card_allocations
      add constraint manual_card_allocations_quantity_check
      check (quantity >= 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'manual_card_allocations_profile_key'
      and conrelid = 'public.manual_card_allocations'::regclass
  ) then
    alter table public.manual_card_allocations
      add constraint manual_card_allocations_profile_key unique (profile_id);
  end if;
end $$;

create index if not exists manual_card_allocations_profile_idx on public.manual_card_allocations (profile_id);
create index if not exists manual_card_allocations_email_idx on public.manual_card_allocations (account_email);

create table if not exists public.manual_card_emails (
  id bigint generated by default as identity primary key,
  allocation_id uuid not null references public.manual_card_allocations(id) on delete cascade,
  purchaser_profile_id uuid not null references public.profiles(id) on delete cascade,
  purchaser_email text not null default '',
  card_index integer not null check (card_index > 0),
  card_name text not null default '',
  card_email text not null default '',
  is_purchaser boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint manual_card_emails_allocation_card_key unique (allocation_id, card_index)
);

alter table public.manual_card_emails
  add column if not exists purchaser_email text not null default '';
alter table public.manual_card_emails
  add column if not exists card_name text not null default '';
alter table public.manual_card_emails
  add column if not exists card_email text not null default '';
alter table public.manual_card_emails
  add column if not exists is_purchaser boolean not null default false;
alter table public.manual_card_emails
  add column if not exists created_at timestamptz not null default now();
alter table public.manual_card_emails
  add column if not exists updated_at timestamptz not null default now();

create index if not exists manual_card_emails_allocation_idx on public.manual_card_emails (allocation_id, card_index);
create index if not exists manual_card_emails_purchaser_idx on public.manual_card_emails (purchaser_profile_id);
create index if not exists manual_card_emails_card_email_idx on public.manual_card_emails (card_email);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists manual_card_allocations_set_updated_at on public.manual_card_allocations;
create trigger manual_card_allocations_set_updated_at
before update on public.manual_card_allocations
for each row
execute function public.set_updated_at();

drop trigger if exists manual_card_emails_set_updated_at on public.manual_card_emails;
create trigger manual_card_emails_set_updated_at
before update on public.manual_card_emails
for each row
execute function public.set_updated_at();

alter table public.manual_card_allocations enable row level security;
alter table public.manual_card_emails enable row level security;

drop policy if exists "manual allocations manager read" on public.manual_card_allocations;
create policy "manual allocations manager read"
on public.manual_card_allocations
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'check.email@residue.com');

drop policy if exists "manual allocations manager insert" on public.manual_card_allocations;
create policy "manual allocations manager insert"
on public.manual_card_allocations
for insert
to authenticated
with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'check.email@residue.com');

drop policy if exists "manual allocations manager update" on public.manual_card_allocations;
create policy "manual allocations manager update"
on public.manual_card_allocations
for update
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'check.email@residue.com')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'check.email@residue.com');

drop policy if exists "manual allocations owner read active" on public.manual_card_allocations;
create policy "manual allocations owner read active"
on public.manual_card_allocations
for select
to authenticated
using (auth.uid() = profile_id and quantity > 0);

drop policy if exists "manual card emails manager read" on public.manual_card_emails;
create policy "manual card emails manager read"
on public.manual_card_emails
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'check.email@residue.com');

drop policy if exists "manual card emails owner read active" on public.manual_card_emails;
create policy "manual card emails owner read active"
on public.manual_card_emails
for select
to authenticated
using (
  auth.uid() = purchaser_profile_id
  and exists (
    select 1
    from public.manual_card_allocations mca
    where mca.id = manual_card_emails.allocation_id
      and mca.profile_id = auth.uid()
      and mca.quantity > 0
      and manual_card_emails.card_index <= mca.quantity
  )
);

drop policy if exists "manual card emails owner insert active" on public.manual_card_emails;
create policy "manual card emails owner insert active"
on public.manual_card_emails
for insert
to authenticated
with check (
  auth.uid() = purchaser_profile_id
  and exists (
    select 1
    from public.manual_card_allocations mca
    where mca.id = manual_card_emails.allocation_id
      and mca.profile_id = auth.uid()
      and mca.quantity > 0
      and manual_card_emails.card_index between 1 and mca.quantity
  )
);

drop policy if exists "manual card emails owner update active" on public.manual_card_emails;
create policy "manual card emails owner update active"
on public.manual_card_emails
for update
to authenticated
using (
  auth.uid() = purchaser_profile_id
  and exists (
    select 1
    from public.manual_card_allocations mca
    where mca.id = manual_card_emails.allocation_id
      and mca.profile_id = auth.uid()
      and mca.quantity > 0
      and manual_card_emails.card_index <= mca.quantity
  )
)
with check (
  auth.uid() = purchaser_profile_id
  and exists (
    select 1
    from public.manual_card_allocations mca
    where mca.id = manual_card_emails.allocation_id
      and mca.profile_id = auth.uid()
      and mca.quantity > 0
      and manual_card_emails.card_index between 1 and mca.quantity
  )
);
