-- Run this in Supabase SQL Editor after link-card-schema.sql.
-- Stores the per-card email assignments for paid purchase invoices.

create table if not exists public.order_card_emails (
  id bigint generated by default as identity primary key,
  invoice_no text not null references public.purchase_invoices(invoice_no) on delete cascade,
  purchaser_profile_id uuid not null references public.profiles(id) on delete cascade,
  purchaser_email text not null default '',
  card_index integer not null check (card_index > 0),
  card_name text not null default '',
  card_email text not null default '',
  is_purchaser boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_card_emails_invoice_card_key unique (invoice_no, card_index)
);

alter table public.order_card_emails
  add column if not exists card_name text not null default '';

create index if not exists order_card_emails_invoice_idx on public.order_card_emails (invoice_no, card_index);
create index if not exists order_card_emails_purchaser_idx on public.order_card_emails (purchaser_profile_id);
create index if not exists order_card_emails_card_email_idx on public.order_card_emails (card_email);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists order_card_emails_set_updated_at on public.order_card_emails;
create trigger order_card_emails_set_updated_at
before update on public.order_card_emails
for each row
execute function public.set_updated_at();

alter table public.order_card_emails enable row level security;

drop policy if exists "order card emails purchaser read" on public.order_card_emails;
create policy "order card emails purchaser read"
on public.order_card_emails
for select
to authenticated
using (
  auth.uid() = purchaser_profile_id
  and exists (
    select 1
    from public.purchase_invoices pi
    where pi.invoice_no = order_card_emails.invoice_no
      and pi.profile_id = auth.uid()
      and upper(coalesce(pi.payment_status, '')) = 'COMPLETE'
  )
);

drop policy if exists "order card emails purchaser write" on public.order_card_emails;
create policy "order card emails purchaser write"
on public.order_card_emails
for all
to authenticated
using (
  auth.uid() = purchaser_profile_id
  and exists (
    select 1
    from public.purchase_invoices pi
    where pi.invoice_no = order_card_emails.invoice_no
      and pi.profile_id = auth.uid()
      and upper(coalesce(pi.payment_status, '')) = 'COMPLETE'
  )
)
with check (
  auth.uid() = purchaser_profile_id
  and exists (
    select 1
    from public.purchase_invoices pi
    where pi.invoice_no = order_card_emails.invoice_no
      and pi.profile_id = auth.uid()
      and upper(coalesce(pi.payment_status, '')) = 'COMPLETE'
  )
);

drop policy if exists "order card emails manager read" on public.order_card_emails;
create policy "order card emails manager read"
on public.order_card_emails
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'check.email@residue.com');
