window.env = {
  SUPABASE_URL: '',
  SUPABASE_ANON_KEY: '',
  SHIPPING_FEE: '',
  SUPABASE_ORDERS_TABLE: '',
  SUPABASE_INVOICES_TABLE: '',
  PAYFAST_PROCESS_URL: '',
  ACCESS_REQUEST_FUNCTION_URL: '',
  ACCESS_CODE_VERIFY_ENDPOINT: '',
  TURNSTILE_SITE_KEY: '0x4AAAAAADAvI_1p6qpg5G_E'
};